Renames guateng to gauteng

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -24,29 +24,29 @@ jobs:
          
     - name: Get flutter dependencies
       run: |
-        cd guateng-wellbeing-mapper-app
+        cd gauteng-wellbeing-mapper-app
         flutter pub get
     
     - name: Statically analyze the Dart code for any errors.
       run: |
-        cd guateng-wellbeing-mapper-app
+        cd gauteng-wellbeing-mapper-app
         flutter analyze --no-fatal-infos --no-fatal-warnings
     
     - name: Run tests for our flutter project.
       run: |
-        cd guateng-wellbeing-mapper-app
+        cd gauteng-wellbeing-mapper-app
         flutter test --coverage --dart-define=FLUTTER_TEST_MODE=true --reporter=expanded --concurrency=1
       continue-on-error: false
         
     - name: Check coverage file exists
       run: |
-        ls -la guateng-wellbeing-mapper-app/coverage/ || echo "Coverage directory not found"
+        ls -la gauteng-wellbeing-mapper-app/coverage/ || echo "Coverage directory not found"
         
     - name: Upload coverage to codecov
       if: always()
       uses: codecov/codecov-action@v5
       with:
-        file: ./guateng-wellbeing-mapper-app/coverage/lcov.info
+        file: ./gauteng-wellbeing-mapper-app/coverage/lcov.info
         token: ${{ secrets.CODECOV_TOKEN }}
         fail_ci_if_error: false
         verbose: false
